"""add cards columns

Revision ID: 28166870d578
Revises: 3062bcf702e6
Create Date: 2026-01-16 22:45:16.711190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28166870d578'
down_revision: Union[str, Sequence[str], None] = '3062bcf702e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card_draws',
    sa.Column('card_draw_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('card_draw_id')
    )
    op.create_table('cards',
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('deck_type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body_text', sa.Text(), nullable=False),
    sa.Column('is_retainable', sa.Boolean(), nullable=False),
    sa.Column('effect_code', sa.String(), nullable=False),
    sa.Column('effect_params', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('card_id')
    )
    op.create_table('jackpot_ledger',
    sa.Column('jackpot_entry_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('jackpot_entry_id')
    )
    op.create_table('transactions',
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.game_id'], ),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_table('turns',
    sa.Column('turn_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.game_id'], ),
    sa.PrimaryKeyConstraint('turn_id')
    )
    op.create_table('movements',
    sa.Column('movement_id', sa.Integer(), nullable=False),
    sa.Column('turn_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['turn_id'], ['turns.turn_id'], ),
    sa.PrimaryKeyConstraint('movement_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movements')
    op.drop_table('turns')
    op.drop_table('transactions')
    op.drop_table('jackpot_ledger')
    op.drop_table('cards')
    op.drop_table('card_draws')
    # ### end Alembic commands ###
