"""base schema

Revision ID: 3062bcf702e6
Revises: 
Create Date: 2026-01-16 18:59:36.104456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3062bcf702e6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('property_groups',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(), nullable=False),
    sa.Column('color_hex', sa.String(), nullable=False),
    sa.Column('house_cost', sa.Integer(), nullable=False),
    sa.Column('hotel_cost', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('group_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('games',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('host_user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('last_saved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['host_user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('game_id')
    )
    op.create_table('spaces',
    sa.Column('space_id', sa.Integer(), nullable=False),
    sa.Column('board_index', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('space_type', sa.String(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['property_groups.group_id'], ),
    sa.PrimaryKeyConstraint('space_id'),
    sa.UniqueConstraint('board_index')
    )
    op.create_table('assets',
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('space_id', sa.Integer(), nullable=False),
    sa.Column('asset_type', sa.String(), nullable=False),
    sa.Column('purchase_price', sa.Integer(), nullable=False),
    sa.Column('mortgage_value', sa.Integer(), nullable=False),
    sa.Column('rent_base', sa.Integer(), nullable=True),
    sa.Column('rent_group', sa.Integer(), nullable=True),
    sa.Column('rent_house_1', sa.Integer(), nullable=True),
    sa.Column('rent_house_2', sa.Integer(), nullable=True),
    sa.Column('rent_house_3', sa.Integer(), nullable=True),
    sa.Column('rent_house_4', sa.Integer(), nullable=True),
    sa.Column('rent_hotel', sa.Integer(), nullable=True),
    sa.Column('rent_tier_2', sa.Integer(), nullable=True),
    sa.Column('rent_tier_3', sa.Integer(), nullable=True),
    sa.Column('rent_tier_4', sa.Integer(), nullable=True),
    sa.Column('utility_mult_single', sa.Integer(), nullable=True),
    sa.Column('utility_mult_double', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.space_id'], ),
    sa.PrimaryKeyConstraint('asset_id'),
    sa.UniqueConstraint('space_id')
    )
    op.create_table('game_players',
    sa.Column('game_player_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('player_name', sa.String(), nullable=False),
    sa.Column('turn_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.game_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('game_player_id'),
    sa.UniqueConstraint('game_id', 'turn_order', name='uq_game_player_turn')
    )
    op.create_table('house_rules',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('starting_cash', sa.Integer(), nullable=False),
    sa.Column('pass_start_bonus', sa.Integer(), nullable=False),
    sa.Column('jackpot_enabled', sa.Boolean(), nullable=True),
    sa.Column('allow_auctions', sa.Boolean(), nullable=True),
    sa.Column('allow_trading', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.game_id'], ),
    sa.PrimaryKeyConstraint('game_id')
    )
    op.create_table('asset_states',
    sa.Column('asset_state_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('owner_game_player_id', sa.Integer(), nullable=True),
    sa.Column('is_mortgaged', sa.Boolean(), nullable=True),
    sa.Column('improvement_level', sa.Integer(), nullable=True),
    sa.Column('has_hotel', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.asset_id'], ),
    sa.ForeignKeyConstraint(['game_id'], ['games.game_id'], ),
    sa.ForeignKeyConstraint(['owner_game_player_id'], ['game_players.game_player_id'], ),
    sa.PrimaryKeyConstraint('asset_state_id'),
    sa.UniqueConstraint('game_id', 'asset_id', name='uq_asset_state_game_asset')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('asset_states')
    op.drop_table('house_rules')
    op.drop_table('game_players')
    op.drop_table('assets')
    op.drop_table('spaces')
    op.drop_table('games')
    op.drop_table('users')
    op.drop_table('property_groups')
    # ### end Alembic commands ###
