"""add trade_sessions table

Revision ID: f5535833a837
Revises: b1c2d3e4f5g6
Create Date: 2026-01-29 18:21:24.798353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5535833a837'
down_revision: Union[str, Sequence[str], None] = 'b1c2d3e4f5g6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trade_sessions',
    sa.Column('trade_session_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('initiator_player_id', sa.Integer(), nullable=False),
    sa.Column('counterparty_player_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('initiator_offer', sa.Text(), nullable=True),
    sa.Column('counterparty_offer', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['counterparty_player_id'], ['game_players.game_player_id'], ),
    sa.ForeignKeyConstraint(['game_id'], ['games.game_id'], ),
    sa.ForeignKeyConstraint(['initiator_player_id'], ['game_players.game_player_id'], ),
    sa.PrimaryKeyConstraint('trade_session_id')
    )
    op.add_column('card_draws', sa.Column('game_id', sa.Integer(), nullable=False))
    op.add_column('card_draws', sa.Column('turn_id', sa.Integer(), nullable=False))
    op.add_column('card_draws', sa.Column('deck_type', sa.String(), nullable=False))
    op.add_column('card_draws', sa.Column('card_id', sa.Integer(), nullable=False))
    op.add_column('card_draws', sa.Column('draw_order', sa.Integer(), nullable=False))
    op.add_column('card_draws', sa.Column('kept_by_player_id', sa.Integer(), nullable=True))
    op.add_column('card_draws', sa.Column('resolved_at', sa.DateTime(), nullable=True))
    op.add_column('card_draws', sa.Column('discarded_at', sa.DateTime(), nullable=True))
    op.add_column('card_draws', sa.Column('notes', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'card_draws', 'turns', ['turn_id'], ['turn_id'])
    op.create_foreign_key(None, 'card_draws', 'game_players', ['kept_by_player_id'], ['game_player_id'])
    op.create_foreign_key(None, 'card_draws', 'cards', ['card_id'], ['card_id'])
    op.create_foreign_key(None, 'card_draws', 'games', ['game_id'], ['game_id'])
    op.alter_column('games', 'game_code',
               existing_type=sa.VARCHAR(length=6),
               nullable=False)
    op.add_column('jackpot_ledger', sa.Column('game_id', sa.Integer(), nullable=False))
    op.add_column('jackpot_ledger', sa.Column('turn_id', sa.Integer(), nullable=True))
    op.add_column('jackpot_ledger', sa.Column('transaction_id', sa.Integer(), nullable=True))
    op.add_column('jackpot_ledger', sa.Column('delta_amount', sa.Integer(), nullable=False))
    op.add_column('jackpot_ledger', sa.Column('balance_after', sa.Integer(), nullable=False))
    op.add_column('jackpot_ledger', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.create_foreign_key(None, 'jackpot_ledger', 'transactions', ['transaction_id'], ['transaction_id'])
    op.create_foreign_key(None, 'jackpot_ledger', 'games', ['game_id'], ['game_id'])
    op.create_foreign_key(None, 'jackpot_ledger', 'turns', ['turn_id'], ['turn_id'])
    op.add_column('movements', sa.Column('game_player_id', sa.Integer(), nullable=False))
    op.add_column('movements', sa.Column('start_space_id', sa.Integer(), nullable=False))
    op.add_column('movements', sa.Column('end_space_id', sa.Integer(), nullable=False))
    op.add_column('movements', sa.Column('movement_type', sa.String(), nullable=False))
    op.add_column('movements', sa.Column('distance', sa.Integer(), nullable=True))
    op.add_column('movements', sa.Column('passed_start', sa.Boolean(), nullable=True))
    op.add_column('movements', sa.Column('notes', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'movements', 'spaces', ['end_space_id'], ['space_id'])
    op.create_foreign_key(None, 'movements', 'game_players', ['game_player_id'], ['game_player_id'])
    op.create_foreign_key(None, 'movements', 'spaces', ['start_space_id'], ['space_id'])
    op.add_column('transactions', sa.Column('turn_id', sa.Integer(), nullable=True))
    op.add_column('transactions', sa.Column('sequence_in_turn', sa.Integer(), nullable=True))
    op.add_column('transactions', sa.Column('player_from_id', sa.Integer(), nullable=True))
    op.add_column('transactions', sa.Column('player_to_id', sa.Integer(), nullable=True))
    op.add_column('transactions', sa.Column('amount', sa.Integer(), nullable=False))
    op.add_column('transactions', sa.Column('transaction_type', sa.String(), nullable=False))
    op.add_column('transactions', sa.Column('asset_id', sa.Integer(), nullable=True))
    op.add_column('transactions', sa.Column('space_id', sa.Integer(), nullable=True))
    op.add_column('transactions', sa.Column('card_id', sa.Integer(), nullable=True))
    op.add_column('transactions', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('transactions', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.create_foreign_key(None, 'transactions', 'game_players', ['player_from_id'], ['game_player_id'])
    op.create_foreign_key(None, 'transactions', 'turns', ['turn_id'], ['turn_id'])
    op.create_foreign_key(None, 'transactions', 'assets', ['asset_id'], ['asset_id'])
    op.create_foreign_key(None, 'transactions', 'game_players', ['player_to_id'], ['game_player_id'])
    op.create_foreign_key(None, 'transactions', 'cards', ['card_id'], ['card_id'])
    op.create_foreign_key(None, 'transactions', 'spaces', ['space_id'], ['space_id'])
    op.add_column('turns', sa.Column('active_game_player_id', sa.Integer(), nullable=False))
    op.add_column('turns', sa.Column('dice_roll_1', sa.Integer(), nullable=True))
    op.add_column('turns', sa.Column('dice_roll_2', sa.Integer(), nullable=True))
    op.add_column('turns', sa.Column('is_double', sa.Boolean(), nullable=True))
    op.add_column('turns', sa.Column('double_count', sa.Integer(), nullable=True))
    op.add_column('turns', sa.Column('started_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.create_foreign_key(None, 'turns', 'game_players', ['active_game_player_id'], ['game_player_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'turns', type_='foreignkey')
    op.drop_column('turns', 'started_at')
    op.drop_column('turns', 'double_count')
    op.drop_column('turns', 'is_double')
    op.drop_column('turns', 'dice_roll_2')
    op.drop_column('turns', 'dice_roll_1')
    op.drop_column('turns', 'active_game_player_id')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'created_at')
    op.drop_column('transactions', 'notes')
    op.drop_column('transactions', 'card_id')
    op.drop_column('transactions', 'space_id')
    op.drop_column('transactions', 'asset_id')
    op.drop_column('transactions', 'transaction_type')
    op.drop_column('transactions', 'amount')
    op.drop_column('transactions', 'player_to_id')
    op.drop_column('transactions', 'player_from_id')
    op.drop_column('transactions', 'sequence_in_turn')
    op.drop_column('transactions', 'turn_id')
    op.drop_constraint(None, 'movements', type_='foreignkey')
    op.drop_constraint(None, 'movements', type_='foreignkey')
    op.drop_constraint(None, 'movements', type_='foreignkey')
    op.drop_column('movements', 'notes')
    op.drop_column('movements', 'passed_start')
    op.drop_column('movements', 'distance')
    op.drop_column('movements', 'movement_type')
    op.drop_column('movements', 'end_space_id')
    op.drop_column('movements', 'start_space_id')
    op.drop_column('movements', 'game_player_id')
    op.drop_constraint(None, 'jackpot_ledger', type_='foreignkey')
    op.drop_constraint(None, 'jackpot_ledger', type_='foreignkey')
    op.drop_constraint(None, 'jackpot_ledger', type_='foreignkey')
    op.drop_column('jackpot_ledger', 'created_at')
    op.drop_column('jackpot_ledger', 'balance_after')
    op.drop_column('jackpot_ledger', 'delta_amount')
    op.drop_column('jackpot_ledger', 'transaction_id')
    op.drop_column('jackpot_ledger', 'turn_id')
    op.drop_column('jackpot_ledger', 'game_id')
    op.alter_column('games', 'game_code',
               existing_type=sa.VARCHAR(length=6),
               nullable=True)
    op.drop_constraint(None, 'card_draws', type_='foreignkey')
    op.drop_constraint(None, 'card_draws', type_='foreignkey')
    op.drop_constraint(None, 'card_draws', type_='foreignkey')
    op.drop_constraint(None, 'card_draws', type_='foreignkey')
    op.drop_column('card_draws', 'notes')
    op.drop_column('card_draws', 'discarded_at')
    op.drop_column('card_draws', 'resolved_at')
    op.drop_column('card_draws', 'kept_by_player_id')
    op.drop_column('card_draws', 'draw_order')
    op.drop_column('card_draws', 'card_id')
    op.drop_column('card_draws', 'deck_type')
    op.drop_column('card_draws', 'turn_id')
    op.drop_column('card_draws', 'game_id')
    op.drop_table('trade_sessions')
    # ### end Alembic commands ###
